name: Deploy Node.js Application with Docker

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  build_and_deploy:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      # step 1: checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # step 2: Set up Docker Buildx (optional, useful for multi-platform builds)
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry)

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build Docker image locally
        run: |
          docker build -t my-app:latest .
      # Step 4: Deploy Docker container locally (run the image)

      - name: Deploy Docker container locally
        run: |

          docker stop my-app || true
          docker rm my-app || true

          docker run -d --name my-app -p 80:8080 my-app:latest

      
      
